"""Draft allowlist of tech concepts for the landing search (D27/D30).
Each entry: (name, category, aliases, wikipedia_title). Built explainers are marked in BUILT.
Verify with checks/verify_allowlist.py before deploy; unverified entries are removed, not shipped.
"""
BUILT = {"bloom filter": "/bloom-filter/"}

CONCEPTS = [
# data structures
("array","data structures",[],"Array (data structure)"),
("linked list","data structures",[],"Linked list"),
("stack","data structures",[],"Stack (abstract data type)"),
("queue","data structures",[],"Queue (abstract data type)"),
("hash table","data structures",["hash map","hashmap","dictionary"],"Hash table"),
("binary search tree","data structures",["bst"],"Binary search tree"),
("b-tree","data structures",["btree","b tree"],"B-tree"),
("heap","data structures",["priority queue"],"Heap (data structure)"),
("trie","data structures",["prefix tree"],"Trie"),
("graph","data structures",[],"Graph (abstract data type)"),
("bloom filter","data structures",["bloom filters"],"Bloom filter"),
("cuckoo filter","data structures",[],"Cuckoo filter"),
("skip list","data structures",[],"Skip list"),
("red-black tree","data structures",["red black tree"],"Red–black tree"),
("lsm tree","data structures",["log-structured merge tree","log structured merge tree"],"Log-structured merge-tree"),
("merkle tree","data structures",["hash tree"],"Merkle tree"),
("ring buffer","data structures",["circular buffer"],"Circular buffer"),
("bitmap","data structures",["bit array","bitset"],"Bit array"),
("hyperloglog","data structures",["hll"],"HyperLogLog"),
("count-min sketch","data structures",["count min sketch"],"Count–min sketch"),
# algorithms
("binary search","algorithms",[],"Binary search"),
("quicksort","algorithms",["quick sort"],"Quicksort"),
("merge sort","algorithms",["mergesort"],"Merge sort"),
("heapsort","algorithms",["heap sort"],"Heapsort"),
("dijkstra's algorithm","algorithms",["dijkstra","shortest path"],"Dijkstra's algorithm"),
("breadth-first search","algorithms",["bfs","breadth first search"],"Breadth-first search"),
("depth-first search","algorithms",["dfs","depth first search"],"Depth-first search"),
("dynamic programming","algorithms",[],"Dynamic programming"),
("big o notation","algorithms",["big o","time complexity"],"Big O notation"),
("recursion","algorithms",[],"Recursion (computer science)"),
("hash function","algorithms",["hashing"],"Hash function"),
("consistent hashing","algorithms",[],"Consistent hashing"),
("pagerank","algorithms",["page rank"],"PageRank"),
("a* search","algorithms",["a star","a*"],"A* search algorithm"),
("two's complement","algorithms",["twos complement"],"Two's complement"),
("floating point","algorithms",["ieee 754"],"Floating-point arithmetic"),
("regular expression","algorithms",["regex","regexp"],"Regular expression"),
("levenshtein distance","algorithms",["edit distance"],"Levenshtein distance"),
("run-length encoding","algorithms",["rle"],"Run-length encoding"),
("huffman coding","algorithms",["huffman"],"Huffman coding"),
("lz77","algorithms",["lempel-ziv"],"LZ77 and LZ78"),
("crc","algorithms",["cyclic redundancy check"],"Cyclic redundancy check"),
("reed-solomon","algorithms",["reed solomon","erasure coding"],"Reed–Solomon error correction"),
("fft","algorithms",["fast fourier transform"],"Fast Fourier transform"),
("monte carlo method","algorithms",["monte carlo"],"Monte Carlo method"),
# networking
("tcp","networking",["transmission control protocol"],"Transmission Control Protocol"),
("udp","networking",[],"User Datagram Protocol"),
("ip address","networking",["ip"],"IP address"),
("dns","networking",["domain name system"],"Domain Name System"),
("http","networking",["hypertext transfer protocol"],"HTTP"),
("https","networking",[],"HTTPS"),
("tls","networking",["ssl"],"Transport Layer Security"),
("websocket","networking",["websockets"],"WebSocket"),
("cdn","networking",["content delivery network"],"Content delivery network"),
("load balancer","networking",["load balancing"],"Load balancing (computing)"),
("nat","networking",["network address translation"],"Network address translation"),
("bgp","networking",[],"Border Gateway Protocol"),
("osi model","networking",["osi"],"OSI model"),
("latency","networking",[],"Latency (engineering)"),
("bandwidth","networking",[],"Bandwidth (computing)"),
("packet switching","networking",[],"Packet switching"),
("mtu","networking",["maximum transmission unit"],"Maximum transmission unit"),
("three-way handshake","networking",["tcp handshake"],"Handshake (computing)"),
("quic","networking",[],"QUIC"),
("http/2","networking",["http2"],"HTTP/2"),
# databases
("sql","databases",[],"SQL"),
("relational database","databases",["rdbms"],"Relational database"),
("nosql","databases",[],"NoSQL"),
("acid","databases",[],"ACID"),
("database index","databases",["index"],"Database index"),
("database transaction","databases",["transaction"],"Database transaction"),
("normalization","databases",["database normalization"],"Database normalization"),
("sharding","databases",["shard"],"Shard (database architecture)"),
("replication","databases",["database replication"],"Replication (computing)"),
("write-ahead log","databases",["wal","write ahead log"],"Write-ahead logging"),
("mvcc","databases",["multiversion concurrency control"],"Multiversion concurrency control"),
("query optimizer","databases",["query planner"],"Query optimization"),
("orm","databases",["object-relational mapping"],"Object–relational mapping"),
("key-value store","databases",["key value store"],"Key–value database"),
("time series database","databases",[],"Time series database"),
("graph database","databases",[],"Graph database"),
("cap theorem","databases",["cap"],"CAP theorem"),
("eventual consistency","databases",[],"Eventual consistency"),
("deadlock","databases",[],"Deadlock (computer science)"),
("connection pool","databases",["connection pooling"],"Connection pool"),
# distributed systems
("consensus","distributed systems",["consensus algorithm"],"Consensus (computer science)"),
("raft","distributed systems",[],"Raft (algorithm)"),
("paxos","distributed systems",[],"Paxos (computer science)"),
("leader election","distributed systems",[],"Leader election"),
("vector clock","distributed systems",[],"Vector clock"),
("lamport timestamp","distributed systems",["logical clock"],"Lamport timestamp"),
("two-phase commit","distributed systems",["2pc","two phase commit"],"Two-phase commit protocol"),
("idempotency","distributed systems",["idempotent"],"Idempotence"),
("message queue","distributed systems",["queue"],"Message queue"),
("publish-subscribe","distributed systems",["pubsub","pub/sub","pub sub"],"Publish–subscribe pattern"),
("microservices","distributed systems",["microservice"],"Microservices"),
("service mesh","distributed systems",[],"Service mesh"),
("circuit breaker","distributed systems",[],"Circuit breaker design pattern"),
("rate limiting","distributed systems",["rate limiter","token bucket"],"Rate limiting"),
("backpressure","distributed systems",[],"Back pressure"),
("gossip protocol","distributed systems",[],"Gossip protocol"),
("byzantine fault tolerance","distributed systems",["bft"],"Byzantine fault"),
("distributed hash table","distributed systems",["dht"],"Distributed hash table"),
("mapreduce","distributed systems",["map reduce"],"MapReduce"),
("crdt","distributed systems",["conflict-free replicated data type"],"Conflict-free replicated data type"),
# operating systems & hardware
("process","operating systems",[],"Process (computing)"),
("thread","operating systems",["threads","multithreading"],"Thread (computing)"),
("virtual memory","operating systems",[],"Virtual memory"),
("paging","operating systems",["page table"],"Memory paging"),
("cache","operating systems",["caching","cpu cache"],"Cache (computing)"),
("lru cache","operating systems",["lru","least recently used"],"Cache replacement policies"),
("mutex","operating systems",["lock"],"Lock (computer science)"),
("semaphore","operating systems",[],"Semaphore (programming)"),
("race condition","operating systems",[],"Race condition"),
("context switch","operating systems",["context switching"],"Context switch"),
("system call","operating systems",["syscall"],"System call"),
("file system","operating systems",["filesystem"],"File system"),
("garbage collection","operating systems",["gc"],"Garbage collection (computer science)"),
("stack overflow","operating systems",[],"Stack overflow"),
("memory leak","operating systems",[],"Memory leak"),
("pipeline","operating systems",["cpu pipeline","instruction pipelining"],"Instruction pipelining"),
("branch prediction","operating systems",[],"Branch predictor"),
("interrupt","operating systems",[],"Interrupt"),
("scheduler","operating systems",["scheduling"],"Scheduling (computing)"),
("container","operating systems",["containers","docker"],"OS-level virtualization"),
("virtual machine","operating systems",["vm","hypervisor"],"Virtual machine"),
("endianness","operating systems",["big endian","little endian"],"Endianness"),
# security & crypto
("public key cryptography","security",["asymmetric encryption","public-key cryptography"],"Public-key cryptography"),
("rsa","security",[],"RSA cryptosystem"),
("aes","security",["symmetric encryption"],"Advanced Encryption Standard"),
("sha-256","security",["sha256","sha"],"SHA-2"),
("digital signature","security",[],"Digital signature"),
("certificate authority","security",["ca","certificate"],"Certificate authority"),
("diffie-hellman","security",["diffie hellman","key exchange"],"Diffie–Hellman key exchange"),
("password hashing","security",["bcrypt","salt"],"Key derivation function"),
("oauth","security",["oauth2"],"OAuth"),
("jwt","security",["json web token"],"JSON Web Token"),
("cors","security",[],"Cross-origin resource sharing"),
("xss","security",["cross-site scripting"],"Cross-site scripting"),
("sql injection","security",[],"SQL injection"),
("csrf","security",["cross-site request forgery"],"Cross-site request forgery"),
("zero-knowledge proof","security",["zero knowledge proof","zkp"],"Zero-knowledge proof"),
("hmac","security",[],"HMAC"),
("man-in-the-middle","security",["mitm"],"Man-in-the-middle attack"),
("two-factor authentication","security",["2fa","mfa"],"Multi-factor authentication"),
("blockchain","security",[],"Blockchain"),
("proof of work","security",[],"Proof of work"),
# web & software
("rest","web",["rest api","restful"],"REST"),
("graphql","web",[],"GraphQL"),
("grpc","web",[],"gRPC"),
("json","web",[],"JSON"),
("protobuf","web",["protocol buffers"],"Protocol Buffers"),
("dom","web",["document object model"],"Document Object Model"),
("event loop","web",[],"Event loop"),
("promise","web",["async await","async"],"Futures and promises"),
("virtual dom","web",[],"Virtual DOM"),
("server-side rendering","web",["ssr"],"Server-side scripting"),
("cookie","web",["cookies"],"HTTP cookie"),
("session","web",[],"Session (computer science)"),
("url","web",["uri"],"URL"),
("base64","web",[],"Base64"),
("unicode","web",["utf-8","utf8"],"Unicode"),
("compiler","software",[],"Compiler"),
("interpreter","software",[],"Interpreter (computing)"),
("just-in-time compilation","software",["jit"],"Just-in-time compilation"),
("abstract syntax tree","software",["ast"],"Abstract syntax tree"),
("bytecode","software",[],"Bytecode"),
("type system","software",["static typing","type checking"],"Type system"),
("closure","software",[],"Closure (computer programming)"),
("immutability","software",["immutable"],"Immutable object"),
("dependency injection","software",[],"Dependency injection"),
("pure function","software",[],"Pure function"),
("unit test","software",["unit testing"],"Unit testing"),
("version control","software",["git"],"Version control"),
("continuous integration","software",["ci","ci/cd"],"Continuous integration"),
("feature flag","software",["feature toggle"],"Feature toggle"),
("semantic versioning","software",["semver"],"Software versioning"),
# machine learning & ai
("neural network","machine learning",["neural networks"],"Neural network (machine learning)"),
("gradient descent","machine learning",[],"Gradient descent"),
("backpropagation","machine learning",["backprop"],"Backpropagation"),
("overfitting","machine learning",[],"Overfitting"),
("transformer","machine learning",["transformers"],"Transformer (deep learning architecture)"),
("attention","machine learning",["attention mechanism","self-attention"],"Attention (machine learning)"),
("embedding","machine learning",["embeddings","word embedding"],"Word embedding"),
("tokenization","machine learning",["tokenizer","bpe","byte pair encoding"],"Byte-pair encoding"),
("large language model","machine learning",["llm"],"Large language model"),
("convolutional neural network","machine learning",["cnn"],"Convolutional neural network"),
("reinforcement learning","machine learning",[],"Reinforcement learning"),
("k-means","machine learning",["kmeans","clustering"],"K-means clustering"),
("decision tree","machine learning",[],"Decision tree learning"),
("random forest","machine learning",[],"Random forest"),
("linear regression","machine learning",[],"Linear regression"),
("logistic regression","machine learning",[],"Logistic regression"),
("cosine similarity","machine learning",[],"Cosine similarity"),
("vector database","machine learning",["vector search"],"Vector database"),
("nearest neighbor search","machine learning",["knn","k-nearest neighbors"],"Nearest neighbor search"),
("dropout","machine learning",[],"Dilution (neural networks)"),
("batch normalization","machine learning",[],"Batch normalization"),
("retrieval-augmented generation","machine learning",["rag"],"Retrieval-augmented generation"),
("diffusion model","machine learning",[],"Diffusion model"),
("perceptron","machine learning",[],"Perceptron"),
("bayes theorem","machine learning",["bayes' theorem","bayesian"],"Bayes' theorem"),
("entropy","machine learning",["information entropy"],"Entropy (information theory)"),
("softmax","machine learning",[],"Softmax function"),
("activation function","machine learning",["relu","sigmoid"],"Activation function"),
("loss function","machine learning",[],"Loss function"),
("cross-validation","machine learning",[],"Cross-validation (statistics)"),
]

def normalize(s):
    s = s.strip().lower()
    return s[:-1] if s.endswith("s") and len(s) > 4 and not s.endswith("ss") else s

def build_index():
    idx = {}
    for name, cat, aliases, wiki in CONCEPTS:
        for key in [name] + aliases:
            idx[normalize(key)] = name
    return idx

if __name__ == "__main__":
    import json, collections
    names = [c[0] for c in CONCEPTS]
    dup = [n for n, k in collections.Counter(names).items() if k > 1]
    print("entries:", len(CONCEPTS), "duplicates:", dup or "none")
    print("by category:", dict(collections.Counter(c[1] for c in CONCEPTS)))
    json.dump([{"name":n,"category":c,"aliases":a,"wiki":w,"path":BUILT.get(n)} for n,c,a,w in CONCEPTS],
              open("allowlist.json","w"), indent=1)
    print("wrote allowlist.json")
